### ISSUE TITLE
Please publish a new version to npm

### ISSUE THREAD

**Issue by mirow** [libreform/react-libre-form#1]
There is a bug in the version 0.4.0 published to npm, but which is fixed in commit  bc3cfcf5c2b35235b3dadc76f34fe49ff86a9f65. 
The error causes a warning message "Warning: Invalid argument supplied to oneOf, expected an instance of array" to be printed to the console.

**Comment by k1sul1** [comment]
Wasn't watching this repository for some reason, I'll take care of it. Luckily it wasn't a form breaker or anything.

Please note that 1.0.0 may contain breaking changes, I'm not sure yet, but the internals of this are going to change a bit with the release of WP Libre Form 2.0.

**Comment by k1sul1** [comment]
Reopen this if 0.4.1 doesn't fix your issue.
