### ISSUE TITLE
Input buttons lose their label

### ISSUE THREAD

**Issue by mirow** [libreform/react-libre-form#5]
A button like `<input type="submit" name="submit" value="Click me"/>` is rendered as `<input type="submit" name="submit" defaultValue="Click me"/>` which causes the label to be displayed as `Submit` instead of `Click me`.

**Comment by k1sul1** [comment]
https://github.com/libreform/react-libre-form#submit-button-value-is-dismissed

Blame React :wink:  

`<button type="submit">Click me</button>` should work.
