### ISSUE TITLE
react-html-parser in /node_modules/react-libre-form/es/lib/parser.js

### ISSUE THREAD

**Issue by D19cannon** [libreform/react-libre-form#6]
Hi,

I installed the library today to test it with the demo that has been given in Gatsby. However, I ran straight into an error.

`./node_modules/react-libre-form/es/lib/parser.js
Module not found: Error: Can't resolve 'html-react-parser' in '/Users/db-dev/projects/gatsby-front/node_modules/react-libre-form/es/lib'`

Obviously, I have react-html-parser installed, but that does not make a difference.

Versions:
 "react": "^16.9.0",
"gatsby": "^2.13.73",
"gatsby-source-wordpress": "^3.1.28",
"react-html-parser": "^2.0.2",
"react-libre-form": "^0.4.1",

**Comment by k1sul1** [comment]
https://github.com/libreform/react-libre-form#dependencies

Easy mistake to make. html-react-parser and react-html-parser are different packages. The difference? Size.

https://bundlephobia.com/result?p=html-react-parser@0.9.1
https://bundlephobia.com/result?p=react-html-parser@2.0.2
